export const accept = {
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [
    '.xlsx',
  ],
  'application/vnd.ms-excel.sheet.macroEnabled.12': ['.xlsm'],
};

export const conceptosHardcodeados = [
  {
    codigo: 'A01',
    descripcion: 'Instrumentos de deuda entre empresas afiliadas',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 1,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4983194',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: '2022-02-24T12:56:36.0117617',
    usuarioUltimaModificacion: 'L0661996',
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A02',
    descripcion: 'Inversiones de residentes en inmuebles en el exterior',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 62,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984221',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A03',
    descripcion: 'Otras inversiones directas de residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 61,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984283',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A04',
    descripcion: 'Títulos de deuda',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 60,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984294',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'A05',
    descripcion: 'Derivados financieros',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 59,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984303',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A06',
    descripcion: 'Préstamos otorgados a no residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 58,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984312',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A07',
    descripcion: 'Depósitos de residentes en el exterior',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Transferencias a cuentas propias cuando residís en Argentina',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 57,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984321',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'A08',
    descripcion: 'Otras inversiones en el exterior de residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Transferencias a cuentas de inversión cuando residís en Argentina y en las que interviene un broker o agente financiero del exterior. Solo podés transferir desde tu cuenta en pesos. El límite es de USD 200 por mes o el equivalente en otra moneda e incluye tus compras de dólares y pagos de servicios con tarjeta de crédito, como Netflix, Spotify, entre otros.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 56,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498433',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A09',
    descripcion: 'Billetes y cheques de viajeros en poder de residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 64,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984339',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A10',
    descripcion:
      'Débito/crédito de moneda extranjera en cuentas locales por transferencias con el exterior',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 55,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984348',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A11',
    descripcion:
      'Suscripción primaria de entidades financieras de títulos valores',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 53,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984358',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A12',
    descripcion:
      'Otras operaciones de compra/venta de entidades financieras de títulos valores',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 52,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984367',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A14',
    descripcion:
      'Ingresos de empresas procesadoras de pagos por compra-venta de bienes. Operaciones de empresas procesadoras de pagos',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 51,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984376',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A15',
    descripcion:
      'Ingresos de divisas vinculadas a exportaciones de bienes pendientes de liquidación',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 51,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984376',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A16',
    descripcion: 'Billetes asociados a operaciones entre residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 50,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984385',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A17',
    descripcion:
      'Transferencias desde/al exterior asociadas a operaciones entre residentes',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 49,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'A18',
    descripcion:
      'Compra de moneda extranjera para adquisición de inmuebles en el país con crédito hipotecario',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 48,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'A19',
    descripcion:
      'Constitución de depósitos en moneda extranjera para aplicar al pago de servicios de deuda',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 47,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'A20',
    descripcion: 'Billetes en moneda extranjera por instrucción judicial',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 46,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'A21',
    descripcion:
      'Billetes en moneda extranjera de representaciones diplomáticas y consulares organismos internacionales y otro personal diplomático acreditado',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 45,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'A23',
    descripcion:
      'Constitución de depósito en el exterior para afectar pago de importación de combustible o energía',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 45,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984394',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'B01',
    descripcion: 'Cobros de exportaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 44,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984403',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B02',
    descripcion: 'Cobros anticipados de exportaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 66,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984412',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: '2022-02-23T18:22:18.8603056',
    usuarioUltimaModificacion: 'l0699786',
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B03',
    descripcion: 'Financiaciones del exterior por exportaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 47,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984421',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: '2021-09-27T13:41:41.220661',
    usuarioUltimaModificacion: 'L0292818',
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B04',
    descripcion: 'Financiación de bancos locales por exportaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 46,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498443',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: '2022-02-24T12:25:46.6368565',
    usuarioUltimaModificacion: 'l0699786',
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'B05',
    descripcion:
      'Pagos anticipados de importaciones de bienes (excepto bienes de capital)',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 54,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984439',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B06',
    descripcion:
      'Pagos diferidos de importaciones de bienes (excepto bienes de capital)',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 65,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984447',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: '2022-08-29T14:44:30.8606165',
    usuarioUltimaModificacion: 'l1000994',
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B07',
    descripcion:
      'Pagos vista de importaciones de bienes (excepto bienes de capital e insumos para la pro-ducción local de bienes)',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 74,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984456',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B08',
    descripcion: 'Pagos por otras compras de bienes al exterior',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 67,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984465',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B09',
    descripcion:
      'Compraventa de bienes sin paso por el país y vendidos a terceros países',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 85,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984474',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B10',
    descripcion:
      'Pagos de deudas comerciales por importaciones de bienes sin registro de ingreso aduane-ro (excepto bienes de capital e insumos para la producción local de bienes)',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 86,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984483',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B11',
    descripcion:
      'Cancelación de garantías comerciales de entidades financieras de importaciones de bienes sin registro de ingreso aduanero',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 84,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984492',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B12',
    descripcion: 'Pagos anticipados de importaciones de bienes de capital',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 83,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984501',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B13',
    descripcion:
      'Pagos con registro de ingreso aduanero pendiente por la importación de medicamentos críticos a ingresar por el beneficiario o bienes del Decreto N° 333/20',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 87,
    origenSistema: 0,
    fechaCreacion: '2020-07-03T20:06:07.1566667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B14',
    descripcion:
      'Cancelación de garantías comerciales de entidades financieras por importaciones de bienes con registro de ingreso aduanero',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 88,
    origenSistema: 0,
    fechaCreacion: '2020-07-03T20:06:07.1633333',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B15',
    descripcion:
      'Pagos de deudas comerciales por la importación de bienes con agencias oficiales de crédito a la exportación o una entidad financiera del exterior o que cuente con garantía otorgada por las mismas',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 90,
    origenSistema: 0,
    fechaCreacion: '2020-08-19T05:52:35.3466667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B16',
    descripcion:
      'Pagos con registro de ingreso aduanero pendiente por la importación de productos o insumos relacionados con la provisión o elaboración local de medicamentos u otros bienes re-lacionados con la atención médica y/o sanitaria de la población',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 91,
    origenSistema: 0,
    fechaCreacion: '2020-08-19T05:52:41.72',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B17',
    descripcion:
      'Pagos de deudas comerciales por la importación de medicamentos críticos de personas jurídicas que tengan a cargo su provisión a pacientes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 92,
    origenSistema: 0,
    fechaCreacion: '2021-07-07T14:47:21.1366667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B18',
    descripcion:
      'Pagos vista de importaciones de insumos para la producción local de bienes',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 95,
    origenSistema: 0,
    fechaCreacion: '2021-10-29T21:47:56.7833333',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B19',
    descripcion:
      'Pagos de deudas comerciales por importaciones de insumos para la producción local de bienes sin registro de ingreso aduanero',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 94,
    origenSistema: 0,
    fechaCreacion: '2021-10-29T21:47:00.8666667',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B20',
    descripcion: 'Pagos vista de importaciones de bienes de capital',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 98,
    origenSistema: 0,
    fechaCreacion: '2022-05-30T00:00:00',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B21',
    descripcion:
      'Pagos de deudas comerciales por importaciones de bienes de capital sin registro de ingreso aduanero',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 99,
    origenSistema: 0,
    fechaCreacion: '2022-05-30T00:00:00',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B22',
    descripcion: 'Pagos diferidos de importaciones de bienes de capital',
    idGrupoDeConceptoDeBoleto: 'a6f827ad-d2df-442b-a952-34d6b305f1b6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 100,
    origenSistema: 0,
    fechaCreacion: '2022-07-04T14:51:33.94',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'B25',
    descripcion: 'Ingresos por cobros de exportaciones de bienes no liquidados',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'B26',
    descripcion:
      'Registro de importaciones de bienes por adjudicación de bonos BOPREAL',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'C01',
    descripcion:
      'Adquisiciones/disposiciones de activos no financieros no producidos',
    idGrupoDeConceptoDeBoleto: 'feee4647-5af5-4d11-a4d1-43ef3118b752',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 82,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498451',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'C02',
    descripcion: 'Transferencias de capital',
    idGrupoDeConceptoDeBoleto: 'feee4647-5af5-4d11-a4d1-43ef3118b752',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 81,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984519',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I01',
    descripcion: 'Intereses del exterior',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 80,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984528',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I02',
    descripcion: 'Intereses locales',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 79,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984536',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'I03',
    descripcion: 'Utilidades y dividendos',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 77,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984545',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I04',
    descripcion: 'Remuneración de empleados',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 76,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984554',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I05',
    descripcion: 'Alquiler de inmuebles',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 75,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984564',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I06',
    descripcion: 'Otras rentas',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 78,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984573',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'I07',
    descripcion: 'Transferencias personales',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'A familiares o personas con quienes tengas algún vínculo, por ayuda o regalo. El límite es de USD 200 por mes o el equivalente en otra moneda e incluye tus compras de dólares y pagos de servicios con tarjeta de crédito, como Netflix, Spotify, entre otros.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 73,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984582',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'I08',
    descripcion: 'Otras transferencias corrientes',
    idGrupoDeConceptoDeBoleto: 'f1b63ba5-a30e-43ec-8a73-caa7dbcfb35f',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 72,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984591',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'N01',
    descripcion: 'No informado por el cliente',
    idGrupoDeConceptoDeBoleto: 'a9c18fdd-f481-40e2-bb61-5c11413f8a62',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 71,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.49846',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P01',
    descripcion: 'Instrumentos de deuda entre empresas afiliadas',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 70,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984609',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P02',
    descripcion: 'Inversiones de no residentes en inmuebles en el país',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 69,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984618',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P03',
    descripcion: 'Otras inversiones directas de no residentes',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 68,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984627',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P04',
    descripcion: 'Títulos de deuda',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 45,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984636',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'P05',
    descripcion: 'Derivados financieros',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 63,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984645',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P06',
    descripcion:
      'Préstamos financieros de organismos internacionales y agencias oficiales de crédito',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 43,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984654',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P07',
    descripcion:
      'Préstamos financieros habilitados para aplicar divisas de exportaciones',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 21,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984662',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P08',
    descripcion: 'Otros préstamos financieros',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 19,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984671',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P09',
    descripcion: 'Líneas de crédito del exterior',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 18,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498468',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P10',
    descripcion: 'Depósitos locales de no residentes',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Transferencias a cuentas propias cuando residís en el exterior',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 17,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984689',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P11',
    descripcion: 'Otras inversiones de no residentes',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 16,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984698',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P12',
    descripcion:
      'Otras financiaciones locales otorgadas por la entidad (excluida la financiación de exportaciones y tarjetas de crédito)',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 15,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984707',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'P13',
    descripcion:
      'Pagos de principal de deudas financieras con el exterior originadas en importaciones de bienes',
    idGrupoDeConceptoDeBoleto: '7e85f64d-44e9-48a8-9346-3ecfb48d45e6',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 89,
    origenSistema: 0,
    fechaCreacion: '2020-07-03T20:06:07.1666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P15',
    descripcion:
      'Compra de residentes para su entrega a la entidad en pago del saldo en moneda extranjera por uso de tarjetas',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 103,
    origenSistema: 0,
    fechaCreacion: '2022-12-01T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'NO',
  },
  {
    codigo: 'P16',
    descripcion:
      'Pagos de principal de deudas financieras con el exterior originadas en importaciones de servicios',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 104,
    origenSistema: 0,
    fechaCreacion: '2022-12-01T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'P17',
    descripcion:
      'Registro de refinanciación de deuda comercial en el marco del punto 20. de la Comunicación "A" 7626',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 105,
    origenSistema: 0,
    fechaCreacion: '2022-12-01T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S01',
    descripcion: 'Mantenimiento y reparaciones',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 14,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984716',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S02',
    descripcion: 'Servicios de fletes',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 13,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984725',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S03',
    descripcion: 'Servicios de transporte de pasajeros',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 12,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984734',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S04',
    descripcion: 'Otros servicios de transportes',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 20,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984742',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S05',
    descripcion: 'Servicios postales y de mensajería',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 11,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984751',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S06',
    descripcion:
      'Viajes (excluidas las operaciones asociadas a retiros y/o consumos con tarjetas de residentes con proveedores no residentes o de no residentes con proveedores argentinos)',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Podés transferir por este concepto solo si estás inscripto/a como agencia de turismo.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 9,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498476',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S07',
    descripcion: 'Servicios de construcción',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 8,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984769',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S08',
    descripcion: 'Primas de seguros',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 7,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984778',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S09',
    descripcion: 'Siniestros',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 6,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984787',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S10',
    descripcion: 'Servicios auxiliares de seguros',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 5,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984796',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S11',
    descripcion: 'Servicios financieros',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 4,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984805',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S12',
    descripcion: 'Servicios de telecomunicaciones',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 3,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984814',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S13',
    descripcion: 'Servicios de informática',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Armado de páginas web, soporte web, mantenimiento de sistemas, entre otros.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 2,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984823',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S14',
    descripcion: 'Servicios de información',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 10,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984832',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S15',
    descripcion: 'Cargos por el uso de la propiedad intelectual',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 22,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984841',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S16',
    descripcion: 'Servicios de investigación y desarrollo',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 32,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498485',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S17',
    descripcion: 'Servicios jurídicos, contables y gerenciales',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 23,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984859',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S18',
    descripcion:
      'Servicios de publicidad, investigación de mercado y encuestas de opinión pública',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 41,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984868',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S19',
    descripcion:
      'Servicios arquitectónicos, de ingeniería y otros servicios técnicos',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 40,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984876',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S20',
    descripcion: 'Servicios de arrendamiento operativo',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 39,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984885',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S21',
    descripcion: 'Servicios relacionados con el comercio',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 38,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984894',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S22',
    descripcion: 'Otros servicios empresariales',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: 'Profesionales y técnicos.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 37,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984903',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S23',
    descripcion: 'Servicios audiovisuales y conexos',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 36,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984912',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S24',
    descripcion: 'Otros servicios personales, culturales y recreativos',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas:
      'Cuotas de afiliación a asociaciones e inscripciones a ferias y exposiciones. Pagos de espectáculos y otras actividades culturales o recreativas.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 35,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.4984921',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S25',
    descripcion: 'Servicios del gobierno',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 34,
    origenSistema: 0,
    fechaCreacion: '2020-04-17T21:42:41.498493',
    usuarioCreacion: null,
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S26',
    descripcion: 'Servicios de salud por empresas de asistencia al viajero',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 93,
    origenSistema: 0,
    fechaCreacion: '2021-09-03T13:40:27.38',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S27',
    descripcion: 'Otros servicios de salud',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: 'Gastos por tratamientos médicos.',
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 96,
    origenSistema: 0,
    fechaCreacion: '2022-01-17T15:22:47.2966667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S28',
    descripcion: 'Enseñanzas educativas',
    idGrupoDeConceptoDeBoleto: '23f226ad-49f2-428d-88fa-9a5ab2b7c558',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 101,
    origenSistema: 0,
    fechaCreacion: '2022-09-20T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S29',
    descripcion:
      'Operaciones asociadas a retiros y/o consumos con tarjetas de residentes con proveedores no residentes o de no residentes con proveedores argentinos',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2022-12-01T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S30',
    descripcion:
      'Servicios de fletes por operaciones de importaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 101,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S31',
    descripcion:
      'Servicios de fletes por operaciones de exportaciones de bienes',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'SI',
  },
  {
    codigo: 'S32',
    descripcion:
      'Ingresos por cobros de exportaciones de servicios no liquidados',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
  {
    codigo: 'S33',
    descripcion:
      'Registro de importaciones de servicios por adjudicación de bonos BOPREAL',
    idGrupoDeConceptoDeBoleto: 'SIN ID',
    grupoDeConceptoDeBoleto: null,
    descripcionParaEmpresas: null,
    descripcionParaPersonasHumanas: null,
    usuarioAutorizante: null,
    fechaDeAutorizacion: null,
    id: 102,
    origenSistema: 0,
    fechaCreacion: '2023-06-27T11:55:09.7666667',
    usuarioCreacion: 'SECOPA',
    fechaEliminacion: null,
    usuarioEliminacion: null,
    fechaDeUltimaModificacion: null,
    usuarioUltimaModificacion: null,
    llevaBeneficiario: 'OPCIONAL',
  },
];
